# sim_unstructured config
num_class: 20
depth_scaling: 2000
topic: /semantic_map
dir: /media/ganlu/PERL-SSD/00000IROS2020/kitti/data_kitti_05/
traversability_img_folder: test_results/

# Information about range-finder data
scan_num: 900 # How many scans to use
max_range: -1 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 4.3

original_size: true
predict: false

ds_resolution: 0.1
free_resolution: 10.0
prior: 0.001
block_depth: 3
