# sim_unstructured config
num_class: 20
fx: 7.188560000000e+02
fy: 7.188560000000e+02
cx: 6.071928000000e+02
cy: 1.852157000000e+02
depth_scaling: 1000
topic: /semantic_map
dir: /media/ganlu/PERL-SSD/00000IROS2020/kitti/data_kitti_15/
traversability_img_folder: traversability/

# Information about range-finder data
scan_num: 100 # How many scans to use
max_range: 15 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 4.3

original_size: true
predict: false

ds_resolution: 0.1
free_resolution: 10.0
prior: 0.001
block_depth: 2
