num_class: 256
fx: 320.0
fy: 320.0
cx: 320.0
cy: 240.0
depth_scaling: 2000
topic: /semantic_map
dir: /media/ganlu/Samsung_T5/000_tro2020/tartanair-release1/abandonedfactory/Easy/P000/
traversability_img_folder: traversability_gt/

# Information about range-finder data
scan_num: 2000 # How many scans to use
max_range: 15 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 4.3

original_size: true
predict: false

ds_resolution: 0.1
free_resolution: 10.0
prior: 0.001
block_depth: 3
